services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: servir-portals-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/src/servir-portals
    ports:
      - 8006:8000
    env_file:
      - ./env/app/.env
    depends_on:
      - db
    
  db:
    image: postgis/postgis
    container_name: servir-portals-db
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d 
      - servir-portals-data:/var/lib/postgresql/data/
    env_file:
      - ./env/db/.env
  pgadmin:
    container_name: servir-portals-pg-admin
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin/.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
     - 8080:80
volumes:
  servir-portals-data:
  pgadmin: