# Generated by Django 3.2 on 2024-05-20 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('areasq_km', models.FloatField(blank=True, null=True)),
                ('areaha', models.BigIntegerField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_of_interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, max_length=254, null=True)),
                ('reg_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Footprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('year', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MineralConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('company_nu', models.BigIntegerField(blank=True, null=True)),
                ('company_na', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mineral_concession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NationalBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('objectid_2', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'national_boundary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('reserve_na', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Protected Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('fid_major_field', models.BigIntegerField(blank=True, db_column='fid_major_', null=True)),
                ('town_name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('district_c', models.CharField(blank=True, max_length=5, null=True)),
                ('regional_c', models.CharField(blank=True, max_length=5, null=True)),
                ('national_c', models.CharField(blank=True, max_length=5, null=True)),
                ('fid_distri', models.BigIntegerField(blank=True, null=True)),
                ('region_1', models.CharField(blank=True, max_length=50, null=True)),
                ('district_1', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_code', models.CharField(blank=True, max_length=16, null=True)),
                ('label', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settlements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('disclaimer', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictGalamseyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_value', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionGalamseyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_value', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveGalamseyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_value', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
