# Generated by Django 3.2 on 2024-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appdetails',
            options={'verbose_name_plural': 'App Details'},
        ),
    ]
