# Generated by Django 3.2 on 2024-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0002_auto_20240520_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='details',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='side_nav_background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='top_nav_background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
