# Generated by Django 3.2 on 2024-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0003_auto_20240520_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='side_nav_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='top_nav_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
