# Generated by Django 3.2 on 2024-05-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0004_auto_20240522_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictGalamseyArea',
        ),
        migrations.DeleteModel(
            name='RegionGalamseyArea',
        ),
        migrations.DeleteModel(
            name='ReserveGalamseyArea',
        ),
        migrations.DeleteModel(
            name='AreaOfInterest',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Footprints',
        ),
        migrations.DeleteModel(
            name='MineralConcession',
        ),
        migrations.DeleteModel(
            name='NationalBoundary',
        ),
        migrations.DeleteModel(
            name='ProtectedArea',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Settlements',
        ),
    ]
