# Generated by Django 3.2 on 2024-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='side_nav_icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
