# Generated by Django 3.2 on 2024-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0007_appdetails_side_nav_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='top_nav_border_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
