# Generated by Django 3.2 on 2024-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0008_appdetails_top_nav_border_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootprintYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('fill_color', models.CharField(blank=True, max_length=50, null=True)),
                ('border_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Footprint Year',
                'verbose_name_plural': 'Footprint Years',
            },
        ),
    ]
