# Generated by Django 3.2 on 2024-05-24 17:00

from django.db import migrations, models
import galamsey_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0010_auto_20240524_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprintyear',
            name='tiff_file',
            field=models.FileField(blank=True, null=True, upload_to=galamsey_portal.models.upload_tiff_location),
        ),
    ]
