# Generated by Django 3.2 on 2024-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0012_datarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='analysis_background',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='analysis_background_size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
