# Generated by Django 3.2 on 2024-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0013_auto_20240624_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFootprintRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_code', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pilot Region',
                'verbose_name_plural': 'Pilot Regions',
            },
        ),
    ]
