# Generated by Django 3.2 on 2024-10-28 15:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey_portal', '0014_pilotfootprintregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceWafordColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_forest_cover', colorfield.fields.ColorField(default='#edf8e9', image_field=None, max_length=25, samples=None)),
                ('open_forest', colorfield.fields.ColorField(default='#a1d99b', image_field=None, max_length=25, samples=None)),
                ('closed_forest', colorfield.fields.ColorField(default='#31a354', image_field=None, max_length=25, samples=None)),
                ('degradation', colorfield.fields.ColorField(default='#FFFF00', image_field=None, max_length=25, samples=None)),
                ('open_forest_loss', colorfield.fields.ColorField(default='#FFA500', image_field=None, max_length=25, samples=None)),
                ('closed_forest_loss', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('open_forest_recovery', colorfield.fields.ColorField(default='#00FFFF', image_field=None, max_length=25, samples=None)),
                ('closed_forest_recovery', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Deforestation Monitoring Color Palette',
                'verbose_name_plural': 'Deforestation Monitoring Color Palettes',
            },
        ),
        migrations.CreateModel(
            name='ReferenceWafordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Deforestation Monitoring Data',
                'verbose_name_plural': 'Deforestation Monitoring Data',
            },
        ),
    ]
