# Generated by Django 4.2 on 2025-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('service', models.CharField(choices=[('GALAMSEY', 'Galamsey Service'), ('CHARCOAL', 'Charcoal Service')], default='GALAMSEY', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('document', models.FileField(upload_to='reports')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
