# Generated by Django 3.2 on 2024-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
