# Generated by Django 4.2 on 2025-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_globalpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('receive_galamsey_email', models.BooleanField(default=False)),
                ('receive_charcoal_email', models.BooleanField(default=False)),
            ],
        ),
    ]
