# Generated by Django 3.2 on 2024-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charcoal_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('disclaimer', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.CharField(blank=True, max_length=800, null=True)),
                ('top_nav_background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('side_nav_background_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'App Details',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
