# Generated by Django 3.2 on 2024-05-27 13:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charcoal_portal', '0005_auto_20240524_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharcoalPointYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('fill_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('border_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Charcoal Point Year',
                'verbose_name_plural': 'Charcoal Point Years',
            },
        ),
    ]
