# Generated by Django 3.2 on 2024-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charcoal_portal', '0007_auto_20240527_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
