# Generated by Django 3.2 on 2024-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charcoal_portal', '0008_datarequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('document', models.FileField(upload_to='reports')),
            ],
        ),
    ]
